[variables]
NIXPACKS_NODE_VERSION = "22.13.1"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit"]
cacheDirectories = ["/root/.npm"]

[phases.build]
cmds = ["npm run build"]
cacheDirectories = ["/app/.next/cache", "/app/node_modules/.cache"]

[start]
cmd = "npm run start"
